##### Numpy

- 수치해석, 수학적 처리를 위한 라이브러리(모듈)
    - Scipy, Pandas, Matploplib
---
- 최신 버전 확인
    - Pandas : https://pandas.pydata.org/
    - Numpy : https://numpy.org/

##### Numpy 설치
```python
!pip install numpy
```

In [1]:
# 현재 버전확인
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
contourpy         1.1.0
cycler            0.11.0
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.11.1
fonttools         4.40.0
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
Jinja2            3.1.2
jupyter_client    8.2.0
jupyter_core      5.3.1
kiwisolver        1.4.4
MarkupSafe        2.1.3
matplotlib        3.7.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
Pillow            9.5.0
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
pyparsing         3.1.0
python-dateutil   2.8.2
py

In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [4]:
#import

import pandas as pd
import numpy as np

##### Numpy 를 쓰는 이유
- python에서 리스트를 만들고 사용처리(1,000,000건) - 260ms
- numpy 로 배열을 만들고 사용처리(1,000,000건) - 34.3ms

In [6]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [7]:
np_arr = np.arange(1_000_000)

In [8]:
# 파이썬 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2 # _ => 사용 안 함

162 ms ± 4.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
# numpy 배열 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

13.7 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 넘파이로 배열 생성, 연산 등

- 파이썬 리스트는 + (리스트끼리), * (숫자만) 연산 밖에 없음
- 행렬(벡터)로 연산하고 싶으면 numpy 배열로 형변환 후에 처리할 것

In [10]:
# 1차원 배열생성
np_arr1 = np.array([1, 3, 5])
np_arr1

array([1, 3, 5])

In [76]:
# 2차원 배열
np_arr2 = np.array([[1, 2, 4], [8, 10, 12]])

np_arr2

array([[ 1,  2,  4],
       [ 8, 10, 12]])

In [72]:
# 3차원 배열생성
np_arr3 = np.array([[[0, 2, 4], [1, 3, 5]], [[5, 9, 12], [1, 23, 2]]])
np_arr3

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 5,  9, 12],
        [ 1, 23,  2]]])

In [15]:
# 파이썬 기본 리스트 (배열)
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [21]:
list2test = [1, 3, 5], [5, 9, 12]
list2test # 튜플로 1차원 배열이 두개 만들어짐 # numpy 에서 허용 안됨

([1, 3, 5], [5, 9, 12])

In [22]:
list2 = [[1, 3, 5], [5, 9, 12]]
list2

[[1, 3, 5], [5, 9, 12]]

In [23]:
# 길이가 4인 1차원 배열을 전부 0으로 채우기
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [24]:
np_arr5 = np.zeros([2, 3]) # 2행 3열
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.random.rand(2, 3)

array([[0.14146599, 0.36556936, 0.10946063],
       [0.48243551, 0.18941684, 0.12453284]])

In [30]:
# list
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
# 파이썬에서 리스트 만들고 numpy 형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# 연산
np_arr7 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np_arr7 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
list(np_arr7) * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [34]:
np_arr7 // 4

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [35]:
# numpy 배열은 더하기 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# 파이썬 list 는 두 리스트를 합침
list(np_arr7) + list(np_arr7)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [37]:
# 비교연산
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [41]:
# 조회
np_arr7[1]

1

In [73]:
# 인덱스 크기를 벗어나면 indexError 예외 발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [44]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [46]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [49]:
np_arr7[3 : 9]

array([3, 4, 5, 6, 7, 8])

In [77]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

12

In [78]:
# 2차원 배열에서 값 조회
np_arr2[1, 2] = 9
np_arr2

array([[ 1,  2,  4],
       [ 8, 10,  9]])

In [55]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

##### 속성

- shape, dtype

In [60]:
# 1차원배열
np_arr1.shape 

(3,)

In [79]:
# 2차원배열
np_arr2.shape

(2, 3)

In [80]:
np_arr2.dtype

dtype('int32')

In [81]:
# Pivot
np_arr2.T

array([[ 1,  8],
       [ 2, 10],
       [ 4,  9]])

In [82]:
# Pivot
np_arr2.T.shape

(3, 2)

##### 기타 함수

In [65]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np_arr8.mean() # 평균

4.5

In [69]:
np_arr8.sum()

45

In [68]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [70]:
np_arr9 = np.random.randn(10)
np_arr9

array([ 1.51415158, -0.04275586,  0.71604286,  0.5558246 ,  0.8958227 ,
        0.08465273,  0.63247833, -0.95790423,  0.92839985,  0.33642827])

In [86]:
np_arr9.sort() # 오름차순 정렬
np_arr9

array([-0.95790423, -0.04275586,  0.08465273,  0.33642827,  0.5558246 ,
        0.63247833,  0.71604286,  0.8958227 ,  0.92839985,  1.51415158])

In [84]:
-np.sort(-np_arr9) # 내림차순 정렬

array([ 1.51415158,  0.92839985,  0.8958227 ,  0.71604286,  0.63247833,
        0.5558246 ,  0.33642827,  0.08465273, -0.04275586, -0.95790423])

##### 테스트용 데이터프레임 예제

In [97]:
# 테스트용 더미데이터프레임 만들기
# 판다스와 조합해서 생성
size = 10
df = pd.DataFrame({
    'class' : [['A', 'B', 'C', 'D', 'F'][np.random.randint(0,3)] for i in range(0, size)],
    'year' : [np.random.randint(2010, 2024) for i in range(0, size)],
    'month' : [np.random.randint(1, 13) for i in range(0, size)],
    'val1' : [np.random.randint(1, 11) for i in range(0, size)],
    'val2' : [np.random.randint(100, 1000) for i in range(0, size)],
    'val3' : [np.random.randint(10000, 20000) for i in range(0, size)]
})
df

class  year  month  val1  val2   val3
0     C  2023      1     9   579  19908
1     A  2018      3     3   958  12171
2     B  2021      2     4   605  19956
3     C  2021      7     9   888  19620
4     B  2021      4     2   116  10132
5     A  2020      7     8   890  17982
6     A  2015      9     9   945  10713
7     B  2014      1     7   866  15477
8     A  2021     11     3   328  19280
9     B  2017      4     7   319  16061